2025-03-26 23:01:06,723 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:01:07,496 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:01:09,425 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/config.py:64]
2025-03-26 23:01:09,425 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:01:09,425 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:01:10,017 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:01:10,017 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:01:16,504 ERROR: Unbehandelte Ausnahme: 'User' object has no attribute 'role' [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:1168]
2025-03-26 23:01:16,504 ERROR: Unbehandelte Ausnahme: 'User' object has no attribute 'role' [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:1168]
2025-03-26 23:01:16,504 INFO: Antwort gesendet: 500 INTERNAL SERVER ERROR [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:01:16,504 INFO: Antwort gesendet: 500 INTERNAL SERVER ERROR [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:01:23,019 INFO: Index-Route wird aufgerufen [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:88]
2025-03-26 23:01:23,019 INFO: Index-Route wird aufgerufen [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:88]
2025-03-26 23:01:23,020 INFO: Versuche, Daten für die Startseite zu laden [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:90]
2025-03-26 23:01:23,020 INFO: Versuche, Daten für die Startseite zu laden [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:90]
2025-03-26 23:01:23,020 INFO: News-Items geladen: 2 [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:92]
2025-03-26 23:01:23,020 INFO: News-Items geladen: 2 [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:92]
2025-03-26 23:01:23,020 INFO: Upcoming Events geladen: 2 [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:94]
2025-03-26 23:01:23,020 INFO: Upcoming Events geladen: 2 [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:94]
2025-03-26 23:01:23,020 INFO: Startseite erfolgreich geladen [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:97]
2025-03-26 23:01:23,020 INFO: Startseite erfolgreich geladen [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:97]
2025-03-26 23:01:23,134 INFO: Antwort gesendet: 200 OK [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:01:23,134 INFO: Antwort gesendet: 200 OK [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:01:23,185 INFO: Antwort gesendet: 304 NOT MODIFIED [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:01:23,185 INFO: Antwort gesendet: 304 NOT MODIFIED [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:01:23,187 INFO: Antwort gesendet: 304 NOT MODIFIED [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:01:23,187 INFO: Antwort gesendet: 304 NOT MODIFIED [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:01:23,189 INFO: Antwort gesendet: 304 NOT MODIFIED [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:01:23,189 INFO: Antwort gesendet: 304 NOT MODIFIED [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:01:23,189 INFO: Antwort gesendet: 304 NOT MODIFIED [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:01:23,189 INFO: Antwort gesendet: 304 NOT MODIFIED [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:01:26,929 ERROR: Unbehandelte Ausnahme: 'User' object has no attribute 'role' [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:1168]
2025-03-26 23:01:26,929 ERROR: Unbehandelte Ausnahme: 'User' object has no attribute 'role' [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:1168]
2025-03-26 23:01:26,931 INFO: Antwort gesendet: 500 INTERNAL SERVER ERROR [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:01:26,931 INFO: Antwort gesendet: 500 INTERNAL SERVER ERROR [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:01:26,976 INFO: Antwort gesendet: 304 NOT MODIFIED [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:01:26,976 INFO: Antwort gesendet: 304 NOT MODIFIED [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:05:59,172 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/config.py:64]
2025-03-26 23:05:59,173 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:05:59,173 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:05:59,928 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:05:59,928 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:06:11,023 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/config.py:64]
2025-03-26 23:06:11,023 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:06:11,023 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:06:11,619 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:06:11,619 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:06:20,209 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/config.py:64]
2025-03-26 23:06:20,209 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:06:20,209 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:06:20,811 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:06:20,811 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:06:39,393 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/config.py:64]
2025-03-26 23:06:39,394 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:06:39,394 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:06:40,102 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:06:40,102 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:06:43,672 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/config.py:64]
2025-03-26 23:06:43,673 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:06:43,673 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:06:44,287 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:06:44,287 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:06:46,733 ERROR: Unbehandelte Ausnahme: 'User' object has no attribute 'role' [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:1168]
2025-03-26 23:06:46,733 ERROR: Unbehandelte Ausnahme: 'User' object has no attribute 'role' [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:1168]
2025-03-26 23:06:46,734 INFO: Antwort gesendet: 500 INTERNAL SERVER ERROR [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:06:46,734 INFO: Antwort gesendet: 500 INTERNAL SERVER ERROR [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:06:47,862 ERROR: Unbehandelte Ausnahme: 'User' object has no attribute 'role' [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:1168]
2025-03-26 23:06:47,862 ERROR: Unbehandelte Ausnahme: 'User' object has no attribute 'role' [in /Users/martin/kuellstedter-dartochsen/app/main/routes.py:1168]
2025-03-26 23:06:47,863 INFO: Antwort gesendet: 500 INTERNAL SERVER ERROR [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:06:47,863 INFO: Antwort gesendet: 500 INTERNAL SERVER ERROR [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:170]
2025-03-26 23:13:42,468 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/config.py:64]
2025-03-26 23:13:42,468 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:13:42,468 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:13:43,245 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:13:43,245 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:13:46,079 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/config.py:64]
2025-03-26 23:13:46,079 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:13:46,079 INFO: Dartochsen startup [in /Users/martin/kuellstedter-dartochsen/app/__init__.py:66]
2025-03-26 23:13:46,678 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
2025-03-26 23:13:46,678 INFO: Firebase erfolgreich initialisiert [in /Users/martin/kuellstedter-dartochsen/app/firebase_manager.py:40]
